version: "3.9"

services:
  mongo:
    image: mongo:7.0
    container_name: coolstuff_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: coolstuff_api
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017
      MONGO_AUTH_DB: auth_db
      MONGO_APP_DB: app_db
      JWT_SECRET: change-me-super-secret
      JWT_ALG: HS256
      ACCESS_TOKEN_EXPIRES_MIN: 60

volumes:
  mongo_data:
