version: "3.9"

services:
  redis:
    image: redis:7
    container_name: coolstuff_redis
    ports:
      - "6379:6379"
  mongo:
    image: mongo:7.0
    container_name: coolstuff_mongo
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: coolstuff_api
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
    environment:
      MONGO_URI: mongodb://mongo:27017
      REDIS_URL: redis://redis:6379
      MONGO_AUTH_DB: auth_db
      MONGO_APP_DB: app_db
      JWT_SECRET: change-me-super-secret
      JWT_ALG: HS256
      ACCESS_TOKEN_EXPIRES_MIN: 60
      CORS_ORIGINS: '["http://localhost:3000","https://cosas-cool.lovable.app/"]'

volumes:
  mongo_data:
